name: Update Readme

on: 
  push:
    - master
  schedule:
  # every day
    - cron: '0 0 * * *'
jobs:
  update_file:
    name: update file
    runs-on: ubuntu-18.04
    env:
      # current repo
      GH_TOKEN: ${{ github.token }}
      MDFILE: example.md
    steps:
      - name: Setup go
        uses: actions/setup-go@v2
          with: 
            go-version: '^1.14.6'
      - name: checkout
        uses: actions/checkout@v2
      - name : run Go
        run: go run ./main
      - name: update repo
        run: |-
          git diff
          git config --global user.email "tz-bot@noreply.fun"
          git config --global user.name "tz-readme-bot"
          git pull
          git add -A
          git commit -m "Updated readme" || exit 0
          git push